/**
 * cdp-proxy.mjs
 *
 * Minimal Node.js CDP Proxy (ES Module) inspired by web-access.
 * Goal: provide an HTTP API that is close to chrome-devtools-mcp tool semantics,
 * so the Skill can "switch drivers" when MCP tools are unavailable.
 *
 * Requirements:
 * - Node.js >= 20 (global fetch available)
 * - Chrome/Chromium started with --remote-debugging-port=<PORT>
 *
 * Usage:
 *   CHROME_PORT=9222 PROXY_PORT=8888 node ./scripts/cdp-proxy.mjs
 *
 * API (subset aligned with MCP tools):
 *   GET  /health
 *   GET  /list_pages
 *   POST /select_page            { "targetId": "..."} OR { "pageId": 0 }
 *   POST /new_page               { "url": "https://example.com" }
 *   POST /navigate_page          { "type":"url", "url":"...", "targetId":"..."? }
 *   POST /evaluate_script        { "function":"() => ...", "args":[...], "targetId":"..."? }
 *   POST /take_snapshot          { "verbose": false, "targetId":"..."? }
 *   POST /click                  { "uid":"e12" | "selector":"button.submit", "targetId":"..."? }
 *   POST /take_screenshot        { "fullPage":true, "filePath":"/tmp/a.png"? , "targetId":"..."? }
 *
 * Notes:
 * - This is a "core framework": stable uid -> DOM mapping is best-effort.
 * - Snapshot is generated by page-eval and returns both a text snapshot and a structured list.
 */
import http from "node:http";
import { writeFileSync } from "node:fs";
import { URL } from "node:url";

// CDP needs a WebSocket client. Use the built-in WebSocket (Node.js 22+).
// This avoids extra dependencies and keeps the proxy portable.
const WebSocketImpl = globalThis.WebSocket;
if (!WebSocketImpl) {
  // eslint-disable-next-line no-console
  console.error(
    "Missing global WebSocket. Please use Node.js >= 22 for CDP proxy mode.",
  );
  process.exit(1);
}

const DEFAULT_PROXY_PORT = Number(process.env.PROXY_PORT || 8888);
const CHROME_HOST = process.env.CHROME_HOST || "127.0.0.1";
const CHROME_PORT = Number(process.env.CHROME_PORT || process.env.PORT || 9222);
const BROWSER_HTTP =
  process.env.BROWSER_HTTP || `http://${CHROME_HOST}:${CHROME_PORT}`;
const MAX_BODY_BYTES = Number(process.env.MAX_BODY_BYTES || 2 * 1024 * 1024);
const CDP_TIMEOUT_MS = Number(process.env.CDP_TIMEOUT_MS || 30_000);

function json(res, statusCode, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(statusCode, {
    "content-type": "application/json; charset=utf-8",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

function text(res, statusCode, body) {
  res.writeHead(statusCode, {
    "content-type": "text/plain; charset=utf-8",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

async function readJsonBody(req) {
  const chunks = [];
  let totalLength = 0;
  for await (const chunk of req) {
    totalLength += chunk.length;
    if (totalLength > MAX_BODY_BYTES) {
      const err = new Error("Request body too large");
      err.statusCode = 413;
      throw err;
    }
    chunks.push(chunk);
  }
  if (!totalLength) return {};
  const buf = Buffer.concat(chunks, totalLength);
  try {
    return JSON.parse(buf.toString("utf8"));
  } catch {
    const err = new Error("Invalid JSON");
    err.statusCode = 400;
    throw err;
  }
}

async function getBrowserWebSocketDebuggerUrl() {
  const resp = await fetch(`${BROWSER_HTTP}/json/version`, { method: "GET" });
  if (!resp.ok)
    throw new Error(
      `Failed to fetch /json/version: ${resp.status} ${resp.statusText}`,
    );
  const data = await resp.json();
  if (!data.webSocketDebuggerUrl)
    throw new Error("Missing webSocketDebuggerUrl");
  return data.webSocketDebuggerUrl;
}

async function probeExistingProxy(port) {
  try {
    const resp = await fetch(`http://127.0.0.1:${port}/health`, {
      method: "GET",
      signal: AbortSignal.timeout(1500),
    });
    if (!resp.ok) return null;
    const data = await resp.json();
    if (!data || data.ok !== true) return null;
    return data;
  } catch {
    return null;
  }
}

class CdpConnection {
  constructor(wsUrl) {
    this.wsUrl = wsUrl;
    this.ws = null;
    this.nextId = 1;
    this.pending = new Map(); // id -> {resolve,reject,timer}
    this.connecting = null;
  }

  async connect() {
    // Ensure concurrent callers share one connecting flow.
    if (this.ws) return;
    if (this.connecting) return this.connecting;

    this.connecting = new Promise((resolve, reject) => {
      const ws = new WebSocketImpl(this.wsUrl);
      this.ws = ws;

      const failAllPending = (err) => {
        for (const [id, p] of this.pending.entries()) {
          clearTimeout(p.timer);
          p.reject(err);
          this.pending.delete(id);
        }
      };

      ws.onmessage = (ev) => {
        let msg;
        try {
          msg = JSON.parse(String(ev.data));
        } catch {
          return;
        }
        if (msg && msg.id && this.pending.has(msg.id)) {
          const p = this.pending.get(msg.id);
          this.pending.delete(msg.id);
          clearTimeout(p.timer);
          if (msg.error)
            p.reject(
              Object.assign(new Error(msg.error.message || "CDP error"), {
                cdpError: msg.error,
              }),
            );
          else p.resolve(msg.result);
        }
        // Events ignored in this minimal framework.
      };

      ws.onopen = () => {
        this.connecting = null;
        resolve();
      };

      ws.onerror = (e) => {
        // If connect fails, reject connect() and clear any pending requests.
        const err = Object.assign(new Error("CDP WebSocket error"), {
          cause: e,
        });
        failAllPending(err);
        this.ws = null;
        this.connecting = null;
        reject(err);
      };

      ws.onclose = () => {
        const err = new Error("CDP WebSocket closed");
        failAllPending(err);
        this.ws = null;
        this.connecting = null;
      };
    });

    return this.connecting;
  }

  async send(method, params = {}, sessionId) {
    await this.connect();
    if (!this.ws) throw new Error("CDP WebSocket is not connected");

    const id = this.nextId++;
    const payload = sessionId
      ? { id, method, params, sessionId }
      : { id, method, params };

    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        if (this.pending.has(id)) {
          this.pending.delete(id);
          reject(
            new Error(
              `CDP request timeout after ${CDP_TIMEOUT_MS}ms: ${method}`,
            ),
          );
        }
      }, CDP_TIMEOUT_MS);
      this.pending.set(id, { resolve, reject, timer });
      this.ws.send(JSON.stringify(payload));
    });
  }

  close() {
    if (this.ws) {
      try {
        this.ws.close();
      } catch {
        // ignore
      }
      this.ws = null;
    }
    for (const [id, p] of this.pending.entries()) {
      clearTimeout(p.timer);
      p.reject(new Error("CDP connection closed"));
      this.pending.delete(id);
    }
  }
}

class TargetManager {
  constructor(conn) {
    this.conn = conn;
    this.targets = new Map(); // targetId -> { sessionId }
    this.selectedTargetId = null;
    this.uidMaps = new Map(); // targetId -> Map(uid -> selector)
  }

  async resolveTargetId({ targetId, pageId }) {
    if (targetId) return targetId;
    if (typeof pageId === "number") {
      const pages = await this.listPages();
      if (pageId < 0 || pageId >= pages.length)
        throw Object.assign(new Error("pageId out of range"), {
          statusCode: 400,
        });
      return pages[pageId].targetId;
    }
    return null;
  }

  async listPages() {
    const { targetInfos } = await this.conn.send("Target.getTargets", {});
    const pages = (targetInfos || [])
      .filter((t) => t.type === "page")
      .map((t, idx) => ({
        pageId: idx,
        targetId: t.targetId,
        url: t.url,
        title: t.title,
        attached: Boolean(t.attached),
      }));
    return pages;
  }

  async ensureAttached(targetId) {
    if (this.targets.has(targetId)) return this.targets.get(targetId);
    const { sessionId } = await this.conn.send("Target.attachToTarget", {
      targetId,
      flatten: true,
    });
    this.targets.set(targetId, { sessionId });
    // Enable essential domains for basic ops.
    await this.conn.send("Page.enable", {}, sessionId);
    await this.conn.send("Runtime.enable", {}, sessionId);
    return { sessionId };
  }

  async clearViewportOverride(sessionId) {
    await this.conn.send("Emulation.clearDeviceMetricsOverride", {}, sessionId);
  }

  async getViewportMetrics(sessionId) {
    const { result, exceptionDetails } = await this.conn.send(
      "Runtime.evaluate",
      {
        expression:
          "({ width: window.innerWidth || document.documentElement.clientWidth || 1280, height: window.innerHeight || document.documentElement.clientHeight || 720, dpr: window.devicePixelRatio || 1 })",
        returnByValue: true,
      },
      sessionId,
    );
    if (exceptionDetails) {
      const err = new Error("Viewport evaluation failed");
      err.cdpError = exceptionDetails;
      err.exceptionDetails = exceptionDetails;
      throw err;
    }
    return result && result.value ? result.value : null;
  }

  cleanupTarget(targetId) {
    this.targets.delete(targetId);
    this.uidMaps.delete(targetId);
    if (this.selectedTargetId === targetId) this.selectedTargetId = null;
  }

  async detachPage({ targetId, pageId }) {
    const tid = await this.resolveTargetId({ targetId, pageId });
    if (!tid)
      throw Object.assign(new Error("Provide targetId or pageId"), {
        statusCode: 400,
      });
    const t = this.targets.get(tid);
    if (t && t.sessionId) {
      await this.conn.send("Target.detachFromTarget", {
        sessionId: t.sessionId,
      });
    }
    this.cleanupTarget(tid);
    return { targetId: tid, detached: true };
  }

  async closePage({ targetId, pageId }) {
    const tid = await this.resolveTargetId({ targetId, pageId });
    if (!tid)
      throw Object.assign(new Error("Provide targetId or pageId"), {
        statusCode: 400,
      });
    // Best-effort: detach first to avoid session build-up.
    const t = this.targets.get(tid);
    if (t && t.sessionId) {
      try {
        await this.conn.send("Target.detachFromTarget", {
          sessionId: t.sessionId,
        });
      } catch {
        // ignore detach errors
      }
    }
    const out = await this.conn.send("Target.closeTarget", { targetId: tid });
    this.cleanupTarget(tid);
    return { targetId: tid, ...out };
  }

  async pickTargetId(explicitTargetId) {
    const targetId = explicitTargetId || this.selectedTargetId;
    if (!targetId)
      throw Object.assign(
        new Error("targetId is required (or call select_page first)"),
        { statusCode: 400 },
      );
    return targetId;
  }

  async selectPage({ targetId, pageId }) {
    if (targetId) {
      this.selectedTargetId = targetId;
      return { targetId };
    }
    if (typeof pageId === "number") {
      const pages = await this.listPages();
      if (pageId < 0 || pageId >= pages.length)
        throw Object.assign(new Error("pageId out of range"), {
          statusCode: 400,
        });
      this.selectedTargetId = pages[pageId].targetId;
      return { targetId: this.selectedTargetId };
    }
    throw Object.assign(new Error("Provide targetId or pageId"), {
      statusCode: 400,
    });
  }

  async newPage(url) {
    const { targetId } = await this.conn.send("Target.createTarget", {
      url: url || "about:blank",
    });
    const { sessionId } = await this.ensureAttached(targetId);
    await this.clearViewportOverride(sessionId);
    this.selectedTargetId = targetId;
    return { targetId };
  }

  async navigatePage({ targetId, type, url }) {
    if (type && type !== "url")
      throw Object.assign(
        new Error("Only type=url is supported in CDP fallback"),
        { statusCode: 400 },
      );
    const tid = await this.pickTargetId(targetId);
    const { sessionId } = await this.ensureAttached(tid);
    await this.clearViewportOverride(sessionId);
    const res = await this.conn.send("Page.navigate", { url }, sessionId);
    return { targetId: tid, ...res };
  }

  async evaluateScript({ targetId, fn, args }) {
    const tid = await this.pickTargetId(targetId);
    const { sessionId } = await this.ensureAttached(tid);
    const uidMap = this.uidMaps.get(tid) || new Map();
    const safeArgs = Array.isArray(args)
      ? args.map((a) =>
          typeof a === "string" && uidMap.has(a) ? uidMap.get(a) : a,
        )
      : [];
    const expr = `(${fn})(${safeArgs.map((a) => JSON.stringify(a)).join(",")})`;
    const { result, exceptionDetails } = await this.conn.send(
      "Runtime.evaluate",
      {
        expression: expr,
        awaitPromise: true,
        returnByValue: true,
      },
      sessionId,
    );
    if (exceptionDetails) {
      const err = new Error("Runtime.evaluate exception");
      err.cdpError = exceptionDetails;
      err.exceptionDetails = exceptionDetails;
      throw err;
    }
    return { targetId: tid, value: result ? result.value : null };
  }

  async takeSnapshot({ targetId, verbose }) {
    const tid = await this.pickTargetId(targetId);
    const { sessionId } = await this.ensureAttached(tid);

    // Generate a best-effort "a11y-like" snapshot with uid mapping.
    // We store uid -> selector so click/screenshot-by-uid can work.
    const snapshotFn = () => {
      function cssEscape(s) {
        // Escape CSS selector special chars. Note: '/' must be escaped in JS regex literal.
        return String(s).replace(
          /([ #;?%&,.+*~\\':!^$\\[\\]()=>|\/@])/g,
          "\\\\$1",
        );
      }
      function selectorFor(el) {
        if (!el || el.nodeType !== 1) return null;
        if (el.id) return "#" + cssEscape(el.id);
        const parts = [];
        let cur = el;
        while (cur && cur.nodeType === 1 && parts.length < 5) {
          const name = cur.tagName.toLowerCase();
          const parent = cur.parentElement;
          if (!parent) {
            parts.unshift(name);
            break;
          }
          const siblings = Array.from(parent.children).filter(
            (c) => c.tagName === cur.tagName,
          );
          if (siblings.length === 1) parts.unshift(name);
          else
            parts.unshift(
              name + ":nth-of-type(" + (siblings.indexOf(cur) + 1) + ")",
            );
          cur = parent;
        }
        return parts.join(">");
      }

      const interactives = Array.from(
        document.querySelectorAll(
          "a,button,input,select,textarea,[role=button],[role=link]",
        ),
      )
        .filter((el) => {
          const r = el.getBoundingClientRect();
          return r.width > 0 && r.height > 0;
        })
        .slice(0, 500);

      const items = interactives
        .map((el, i) => {
          const uid = "e" + (i + 1);
          const role = el.getAttribute("role") || el.tagName.toLowerCase();
          const name = (
            el.getAttribute("aria-label") ||
            el.innerText ||
            el.value ||
            ""
          )
            .trim()
            .slice(0, 80);
          const selector = selectorFor(el);
          return { uid, role, name, selector };
        })
        .filter((x) => x.selector);

      const text = items
        .map((x) => `${x.uid}  ${x.role}  ${x.name}`)
        .join("\\n");
      return { items, text, url: location.href, title: document.title };
    };

    const { result, exceptionDetails } = await this.conn.send(
      "Runtime.evaluate",
      {
        expression: `(${snapshotFn.toString()})()`,
        returnByValue: true,
      },
      sessionId,
    );
    if (exceptionDetails) {
      const err = new Error("Snapshot evaluation failed");
      err.cdpError = exceptionDetails;
      err.exceptionDetails = exceptionDetails;
      throw err;
    }

    const value =
      result && result.value ? result.value : { items: [], text: "" };
    const map = new Map();
    for (const it of value.items || []) map.set(it.uid, it.selector);
    this.uidMaps.set(tid, map);

    // Align with MCP take_snapshot: return a text snapshot (human readable) + elements.
    return {
      targetId: tid,
      verbose: Boolean(verbose),
      snapshotText: value.text || "",
      elements: value.items || [],
      page: { url: value.url || null, title: value.title || null },
    };
  }

  async click({ targetId, uid, selector }) {
    const tid = await this.pickTargetId(targetId);
    const { sessionId } = await this.ensureAttached(tid);
    const uidMap = this.uidMaps.get(tid) || new Map();
    const sel = selector || (uid ? uidMap.get(uid) : null);
    if (!sel)
      throw Object.assign(
        new Error(
          "Provide selector or uid (run take_snapshot first to get uids)",
        ),
        { statusCode: 400 },
      );

    const clickFn = (s) => {
      const el = document.querySelector(s);
      if (!el) return { ok: false, error: "element not found", selector: s };
      el.click();
      return { ok: true, selector: s };
    };

    const { result, exceptionDetails } = await this.conn.send(
      "Runtime.evaluate",
      {
        expression: `(${clickFn.toString()})(${JSON.stringify(sel)})`,
        returnByValue: true,
      },
      sessionId,
    );
    if (exceptionDetails) {
      const err = new Error("Click evaluation failed");
      err.cdpError = exceptionDetails;
      err.exceptionDetails = exceptionDetails;
      throw err;
    }
    return {
      targetId: tid,
      ...(result && result.value ? result.value : { ok: false }),
    };
  }

  async takeScreenshot({ targetId, fullPage, filePath }) {
    const tid = await this.pickTargetId(targetId);
    const { sessionId } = await this.ensureAttached(tid);

    const persistScreenshot = (data) => {
      if (filePath) {
        writeFileSync(filePath, Buffer.from(data, "base64"));
        return {
          targetId: tid,
          filePath,
          bytes: Buffer.from(data, "base64").length,
        };
      }
      return { targetId: tid, data }; // base64 png
    };

    if (fullPage) {
      // Full-page capture must not mutate the page viewport. We clear any stale
      // override left by previous runs, read the current real viewport, and then
      // capture beyond the viewport using a clip.
      await this.clearViewportOverride(sessionId);
      const viewport = await this.getViewportMetrics(sessionId);
      const { contentSize, cssContentSize } = await this.conn.send(
        "Page.getLayoutMetrics",
        {},
        sessionId,
      );
      // `Page.captureScreenshot` expects clip dimensions in CSS pixels.
      // On newer Chrome builds, `cssContentSize` is the reliable source.
      // Falling back to legacy `contentSize` can produce over-tall screenshots
      // on HiDPI displays, so we only use it when css metrics are unavailable.
      const cssWidth =
        (cssContentSize && cssContentSize.width) ||
        (contentSize && contentSize.width) ||
        (viewport && viewport.width) ||
        1;
      const cssHeight =
        (cssContentSize && cssContentSize.height) ||
        (contentSize && contentSize.height) ||
        (viewport && viewport.height) ||
        1;
      const clip = {
        x: 0,
        y: 0,
        width: Math.max(
          1,
          Math.ceil(
            Math.max(viewport && viewport.width ? viewport.width : 1, cssWidth),
          ),
        ),
        height: Math.max(1, Math.ceil(cssHeight)),
        scale: 1,
      };
      const { data } = await this.conn.send(
        "Page.captureScreenshot",
        {
          format: "png",
          fromSurface: true,
          captureBeyondViewport: true,
          clip,
        },
        sessionId,
      );
      return persistScreenshot(data);
    }

    const { data } = await this.conn.send(
      "Page.captureScreenshot",
      {
        format: "png",
        fromSurface: true,
      },
      sessionId,
    );
    return persistScreenshot(data);
  }
}

async function main() {
  const existingProxy = await probeExistingProxy(DEFAULT_PROXY_PORT);
  if (existingProxy) {
    // eslint-disable-next-line no-console
    console.log(
      `Reusing existing CDP Proxy on http://127.0.0.1:${DEFAULT_PROXY_PORT} (chrome: ${existingProxy.browserHttp || "unknown"})`,
    );
    return;
  }

  const wsUrl = await getBrowserWebSocketDebuggerUrl();
  const conn = new CdpConnection(wsUrl);
  await conn.connect();
  // Auto-discover targets; no attach until needed.
  const tm = new TargetManager(conn);

  const server = http.createServer(async (req, res) => {
    try {
      const u = new URL(
        req.url || "/",
        `http://${req.headers.host || "localhost"}`,
      );

      if (req.method === "GET" && u.pathname === "/health") {
        return json(res, 200, { ok: true, browserHttp: BROWSER_HTTP });
      }

      if (req.method === "GET" && u.pathname === "/list_pages") {
        const pages = await tm.listPages();
        return json(res, 200, { pages });
      }

      if (req.method === "POST" && u.pathname === "/select_page") {
        const body = await readJsonBody(req);
        const out = await tm.selectPage({
          targetId: body.targetId,
          pageId: body.pageId,
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/new_page") {
        const body = await readJsonBody(req);
        const out = await tm.newPage(body.url);
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/navigate_page") {
        const body = await readJsonBody(req);
        const out = await tm.navigatePage({
          targetId: body.targetId,
          type: body.type || "url",
          url: body.url,
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/evaluate_script") {
        const body = await readJsonBody(req);
        if (!body.function)
          throw Object.assign(new Error("Missing field: function"), {
            statusCode: 400,
          });
        const out = await tm.evaluateScript({
          targetId: body.targetId,
          fn: body.function,
          args: body.args || [],
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/take_snapshot") {
        const body = await readJsonBody(req);
        const out = await tm.takeSnapshot({
          targetId: body.targetId,
          verbose: Boolean(body.verbose),
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/click") {
        const body = await readJsonBody(req);
        const out = await tm.click({
          targetId: body.targetId,
          uid: body.uid,
          selector: body.selector,
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/take_screenshot") {
        const body = await readJsonBody(req);
        const out = await tm.takeScreenshot({
          targetId: body.targetId,
          fullPage: body.fullPage !== false,
          filePath: body.filePath,
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/detach_page") {
        const body = await readJsonBody(req);
        const out = await tm.detachPage({
          targetId: body.targetId,
          pageId: body.pageId,
        });
        return json(res, 200, out);
      }

      if (req.method === "POST" && u.pathname === "/close_page") {
        const body = await readJsonBody(req);
        const out = await tm.closePage({
          targetId: body.targetId,
          pageId: body.pageId,
        });
        return json(res, 200, out);
      }

      return text(res, 404, "Not Found");
    } catch (e) {
      const status = e && e.statusCode ? e.statusCode : 500;
      return json(res, status, {
        ok: false,
        error: String(e && e.message ? e.message : e),
        details: e && e.cdpError ? e.cdpError : undefined,
      });
    }
  });

  server.listen(DEFAULT_PROXY_PORT, "127.0.0.1", () => {
    // Keep output short and copy-pastable.
    // This proxy is meant to be started/managed by the Agent when MCP is unavailable.
    // eslint-disable-next-line no-console
    console.log(
      `CDP Proxy listening on http://127.0.0.1:${DEFAULT_PROXY_PORT} (chrome: ${BROWSER_HTTP})`,
    );
  });

  const shutdown = async (signal) => {
    // eslint-disable-next-line no-console
    console.log(`Shutting down CDP Proxy (${signal})...`);
    await new Promise((resolve) => server.close(() => resolve()));
    conn.close();
    process.exit(0);
  };

  process.on("SIGINT", () => void shutdown("SIGINT"));
  process.on("SIGTERM", () => void shutdown("SIGTERM"));
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error("CDP Proxy failed to start:", e);
  process.exit(1);
});
